# Generated by Django 5.0 on 2024-01-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer_order',
            name='status',
            field=models.CharField(choices=[('Deliverd', 'Deliverd'), ('Confirmed', 'Confirmed'), ('Cooking', 'Cooking'), ('Ready Delivery', 'Ready Delivery')], default='Deliverd', max_length=20),
            preserve_default=False,
        ),
    ]
