# Generated by Django 5.0 on 2024-01-07 09:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        
    ]
