# Generated by Django 5.0 on 2024-01-01 18:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cooking', 'Cooking'), ('Ready Delivery', 'Ready Delivery'), ('Deliverd', 'Deliverd'), ('Checked Out', 'Checked Out')], default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
