# Generated by Django 5.0 on 2023-12-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
    ]
