# Generated by Django 5.0 on 2024-01-07 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_order_is_deleted_customer_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_order',
            name='is_deleted',
        ),
    ]
