# Generated by Django 5.0 on 2023-12-30 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_order_isdeleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_order',
            old_name='isdeleted',
            new_name='is_deleted',
        ),
    ]
