# Generated by Django 5.0 on 2024-01-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_order_is_delete_customer_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='status',
            field=models.CharField(choices=[('Deliverd', 'Deliverd'), ('Confirmed', 'Confirmed'), ('Cooking', 'Cooking'), ('Ready Delivery', 'Ready Delivery'), ('Checked Out', 'Checked Out')], default='Confirmed', max_length=20),
        ),
    ]
