# Generated by Django 5.0 on 2024-01-08 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_order',
            old_name='is_delete',
            new_name='is_deleted',
        ),
    ]
