# Generated by Django 5.0 on 2023-12-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_isdeleted_customer_order_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
