# Generated by Django 5.0 on 2024-01-08 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_order_status'),
    ]

    operations = [
        
    ]
