# Generated by Django 5.0 on 2024-01-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_rename_is_delete_customer_order_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_order',
            name='status',
            field=models.CharField(choices=[('Deliverd', 'Deliverd'), ('Confirmed', 'Confirmed'), ('Cooking', 'Cooking'), ('Ready_Delivery', 'Ready_Delivery'), ('Checked Out', 'Checked Out')], default='Confirmed', max_length=20),
        ),
    ]
