# Generated by Django 5.0 on 2023-12-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_order_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_order',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True),
        ),
    ]
