# Generated by Django 5.0 on 2023-12-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_order_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_order',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
