# Generated by Django 5.0 on 2023-12-24 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        
    ]
