# Generated by Django 5.0 on 2023-12-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_delete_add_category'),
    ]

    operations = [
        
    ]
