# Generated by Django 5.0 on 2023-12-29 04:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_order_table_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('confirmed', 'Confirmed'), ('cooking', 'Cooking'), ('ready_delivery', 'Ready for Delivery')], default='confirmed', max_length=20),
        ),
    ]
