# Generated by Django 5.0 on 2023-12-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_delete_otpcode'),
    ]

    operations = [
        
    ]
