# Generated by Django 5.0 on 2023-12-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_delete_otpcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCODE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('code', models.PositiveSmallIntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
