# Generated by Django 5.0 on 2023-12-19 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_category_item'),
    ]

    operations = [
        
    ]
