# Generated by Django 5.0 on 2024-01-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_otpcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffe_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
