# Generated by Django 5.0 on 2023-12-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_remove_order_status_order_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('deliverd', 'تحویل شده'), ('Confirmed', 'تایید شده'), ('Cooking', 'در حال پخت'), ('Ready Delivery', 'آماده تحویل')], default='deliverd', max_length=20),
            preserve_default=False,
        ),
    ]
