# Generated by Django 5.0 on 2023-12-27 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_user'),
    ]

    operations = [
        
    ]
