# Generated by Django 5.0 on 2024-01-08 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_coffeinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoffeInfo',
            new_name='CafeInfo',
        ),
    ]
