# Generated by Django 5.0 on 2023-12-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Deliverd', 'Deliverd'), ('Confirmed', 'Confirmed'), ('Cooking', 'Cooking'), ('Ready Delivery', 'Ready Delivery')], max_length=20),
        ),
    ]
