# Generated by Django 5.0 on 2023-12-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
